name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Update version in pom.xml
      run: |
        RELEASE_VERSION=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//')
        mvn versions:set -DnewVersion=${RELEASE_VERSION} -DgenerateBackupPoms=false

    - name: Update the lock
      run: mvn io.mvnpm:locker-maven-plugin:0.0.6:lock
    
    - name: Build with Maven
      run: mvn clean install -Dnative -DskipTests
    
    - name: Log in to Quay.io
      run: echo "${{ secrets.QUAY_PASSWORD }}" | docker login quay.io -u "${{ secrets.QUAY_USERNAME }}" --password-stdin
    
    - name: Build Docker image
      run: docker build -f src/main/docker/Dockerfile.native-micro -t pkruger/mvnpm:${{ github.event.release.tag_name }} .

    - name: Tag Docker image
      run: docker tag pkruger/mvnpm:${{ github.event.release.tag_name }} quay.io/pkruger/mvnpm:${{ github.event.release.tag_name }}
    
    - name: Push Docker image to Quay.io
      run: docker push quay.io/pkruger/mvnpm:${{ github.event.release.tag_name }}

  
  update_version:
    runs-on: ubuntu-latest
    needs: release

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Increment patch version and update to SNAPSHOT
      run: |
        RELEASE_VERSION=$(echo ${{ github.event.release.tag_name }} | sed 's/^v//')
        IFS='.' read -r MAJOR MINOR PATCH <<< "${RELEASE_VERSION}"
        NEXT_PATCH_VERSION="$MAJOR.$MINOR.$((PATCH + 1))-SNAPSHOT"
        mvn versions:set -DnewVersion=${NEXT_PATCH_VERSION} -DgenerateBackupPoms=false
    
    - name: Commit and push changes to a new branch
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -b update-version-${{ github.event.release.tag_name }}
        git add pom.xml
        git commit -m "Bump version to ${NEXT_PATCH_VERSION}"
        git push origin update-version-${{ github.event.release.tag_name }}

    - name: Create a pull request
      id: create_pr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Bump version to ${NEXT_PATCH_VERSION}"
        branch: update-version-${{ github.event.release.tag_name }}
        title: "Bump version to ${NEXT_PATCH_VERSION}"
        body: "Automatically created by GitHub Actions. Bump version to ${NEXT_PATCH_VERSION}."
        labels: version-update
        base: main
    
    - name: Log pull request number
      run: echo "Pull request number: ${{ steps.create_pr.outputs.pull-request-number }}"

    - name: Automatically merge the pull request (optional)
      if: ${{ steps.create_pr.outputs.pull-request-number != '' }}
      uses: "peter-evans/enable-pull-request-automerge@v2"
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
        merge-method: "squash"
